---
all:
- &1
  id: '10001'
  name: コメダブレンド
  description: 厳選した豆からじっくり丁寧に抽出したコメダ珈琲店伝統の味。濃厚なフレッシュと砂糖の両方を入れるのがオススメです。
- &2
  id: '10002'
  name: アメリカン
  description: 軽くて飲みやすく、コーヒーの旨味を楽しめます。
- &3
  id: '10003'
  name: カフェオーレ
  description: やわらかでマイルドな味わい。コーヒーとミルクのこだわりブレンドです。
- &4
  id: '10004'
  name: ミルクコーヒー
  description: ミルクがいっぱいで飲みやすくまろやかです。
- &5
  id: '10005'
  name: ウインナーコーヒー
  description: とろけるホイップクリームとコーヒーの深いコクをお楽しみください。
- &6
  id: '10007'
  name: 蜂蜜オーレウインナー
  description: |-
    蜂蜜の優しい甘さ感じるカフェオーレに、とろけるホイップがよく合う一杯です。
    ※本商品には「はちみつ」を使用しているため、1歳未満の乳児には与えないでください。
- &7
  id: '10008'
  name: コメ黒
  description: |-
    コクのあるブラジル最上級グレードの豆をベースに華やかに香り高いキリマンジャロをブレンドしました。
    ※ストレートでお楽しみいただくためフレッシュはお付けしておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &8
  id: '10009'
  name: カフェインレスコーヒー
  description: |-
    良質なコロンビア産の豆を100%使用したコーヒーです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &9
  id: '10013'
  name: コメダブレンド たっぷりサイズ
  description: いつものコメダブレンドがたっぷり約1.5倍です！
- &10
  id: '10014'
  name: アメリカン たっぷりサイズ
  description: アメリカンを約1.5倍のたっぷりサイズでお楽しみください。
- &11
  id: '10015'
  name: カフェオーレ たっぷりサイズ
  description: カフェオーレを約1.5倍のたっぷりサイズでお楽しみください。
- &12
  id: '10016'
  name: ミルクコーヒー たっぷりサイズ
  description: ミルクコーヒーを約1.5倍のたっぷりサイズでお楽しみください。
- &13
  id: '10017'
  name: ホットミルク たっぷりサイズ
  description: ミルクを約1.5倍のたっぷりサイズでお楽しみください。
- &14
  id: '10021'
  name: アイスコーヒー
  description: |-
    独特の味とコクを引きたてるために最初から甘味がついています。ぜひフレッシュも入れてお召し上がりください。
    ※甘味抜き・別添えが可能です。
- &15
  id: '10022'
  name: アイスオーレ
  description: 深いコクのコーヒーとミルクのハーモニーをお楽しみください。
- &16
  id: '10023'
  name: アイスミルクコーヒー
  description: コーヒーとミルクのやさしい味わいをアイスでもどうぞ。
- &17
  id: '10024'
  name: アイスウインナー
  description: アイスコーヒーに相性抜群のホイップをのせました。
- &18
  id: '10025'
  name: クリームコーヒー
  description: アイスコーヒーにソフトクリームの山がそびえ立ちます。
- &19
  id: '10026'
  name: クリームオーレ
  description: アイスオーレにソフトクリームの山がそびえ立ちます。
- &20
  id: '10027'
  name: 蜂蜜アイスコーヒー
  description: |-
    蜂蜜の香りと甘みがコーヒーの旨味をぐっと引きたてます。
    ※本商品には「はちみつ」を使用しているため、1歳未満の乳児には与えないでください。
- &21
  id: '10028'
  name: ジェリコ 元祖
  description: コーヒージェリーとアイスコーヒーを組み合わせて、仕上げにホイップをのせたほろ苦い大人の飲むスイーツ。
- &22
  id: '10029'
  name: カフェインレスアイスコーヒー
  description: |-
    良質なコロンビア産の豆を100%使用したアイスコーヒーです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &23
  id: '10033'
  name: プレミアムコーヒー Sophia
  description: |-
    程よい苦味とやわらかな酸味雑味がなく、コクはありながらすっきりとした後味。
    ※ストレートでお楽しみいただくためフレッシュはお付けしておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &24
  id: '10034'
  name: アイスコーヒー たっぷりサイズ
  description: たっぷり約1.5倍！特製ジョッキでお楽しみください。
- &25
  id: '10035'
  name: アイスオーレ たっぷりサイズ
  description: たっぷり約1.5倍！アイスオーレをたっぷりサイズでお楽しみください。
- &26
  id: '10036'
  name: アイスミルクコーヒー たっぷりサイズ
  description: たっぷり約1.5倍！アイスミルクコーヒーをたっぷりサイズでお楽しみください。
- &27
  id: '10037'
  name: アイスミルク たっぷりサイズ
  description: たっぷり約1.5倍！アイスミルクをたっぷりサイズでお楽しみください。
- &28
  id: '10041'
  name: アイスコーヒー　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！アイスコーヒーをでらたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &29
  id: '10042'
  name: アイスオーレ　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！アイスオーレをでらたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &30
  id: '10043'
  name: アイスミルクコーヒー　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！アイスミルクコーヒーをでらたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &31
  id: '10044'
  name: アイスミルク　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！アイスミルクをでらたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &32
  id: '10048'
  name: 紅茶　レモン
  description: レモンティーでお楽しみください。
- &33
  id: '10049'
  name: 紅茶　ミルク
  description: ミルクティーでお楽しみください。
- &34
  id: '10050'
  name: 紅茶　ストレート
  description: スリランカ産茶葉使用。
- &35
  id: '10051'
  name: お伊勢さんの和紅茶 「瑞」
  description: "三重県産の茶葉を使用した風味豊かな和紅茶です。ポットでお楽しみいただけます。  \n※この商品には紅茶の風味を引きたてるためにスリランカ産茶葉も使用しております。\n※ポットサービスはホットのみとなります。\n※紅茶本来の風味をお楽しみいただくため、ストレートのみでの提供となります。\n※店舗により販売状況が異なります。詳しくは店舗にご確認ください。"
- &36
  id: '10052'
  name: アイスレモンティー
  description: レモンティーでお楽しみください。
- &37
  id: '10053'
  name: アイスミルクティー
  description: ミルクティーでお楽しみください。
- &38
  id: '10054'
  name: アイスストレートティー
  description: アールグレイです。
- &39
  id: '10056'
  name: お伊勢さんの和紅茶 「瑞」アイス
  description: "三重県産の茶葉を使用した風味豊かな和紅茶です。 \n※この商品には紅茶の風味を引きたてるためにスリランカ産茶葉も使用しております。\n※ポットサービスはホットのみとなります。\n※紅茶本来の風味をお楽しみいただくため、ストレートのみでの提供となります。\n※店舗により販売状況が異なります。詳しくは店舗にご確認ください。"
- &40
  id: '10057'
  name: ホットミルク
  description: ほっと落ち着く、やさしい味わいです。
- &41
  id: '10058'
  name: アイスミルク
  description: ほのかに甘く、お子様にもおすすめです。
- &42
  id: '10059'
  name: コーンスープ
  description: じんわり温かくやさしい味わいです。お食事と一緒にどうぞ。
- &43
  id: '10060'
  name: ホットココア
  description: カカオが香るクリーミーなココアに、ホイップクリームを載せた贅沢な一杯です。
- &44
  id: '10061'
  name: アイスココア
  description: アイスココアの上にソフトクリームがそびえ立ちます。
- &45
  id: '10062'
  name: メロンソーダ
  description: |-
    メロンソーダを見た目も可愛いブーツグラスでどうぞ。
    ※メロンソーダにメロン果汁は含まれておりません。
- &46
  id: '10063'
  name: クリームソーダ
  description: |-
    懐かしのクリームソーダを見た目も可愛いブーツグラスでどうぞ。
    ※メロンソーダにメロン果汁は含まれておりません。
- &47
  id: '10064'
  name: コーラ
  description: どの年代にも人気の炭酸ドリンクです。レモンを添えた喫茶店風をお楽しみください。
- &48
  id: '10065'
  name: オレンジジュース
  description: 果汁100%(濃縮還元)のオレンジジュース。まんまるだるまグラスで気分もウキウキ！
- &49
  id: '10066'
  name: ミックスジュース
  description: フルーツとミルクで美味しく仕上げました。
- &50
  id: '10067'
  name: サマージュース
  description: |-
    甘夏のつぶつぶ食感が楽しい特製ジュースです。
    ※甘夏果汁約30％使用。
- &51
  id: '10069'
  name: 生レモンスカッシュ
  description: 新鮮なレモンをギュッとしぼった爽やかな味わいです。コロンと可愛いブーツグラスでどうぞ。
- &52
  id: '10070'
  name: コーヒーシェーク
  description: ソフトクリームがとろける、タル製グラスに入ったコーヒー風味の特製デザートドリンクです。
- &53
  id: '10071'
  name: ストロベリーシェーク
  description: ソフトクリームがとろける、イチゴ風味のコメダ特製飲むデザートです。※ストロベリーシェークにいちご果汁は含まれておりません。
- &54
  id: '10074'
  name: バナナジュース
  description: バナナとミルクで美味しく仕上げました。
- &55
  id: '10092'
  name: メロンソーダ　たっぷりサイズ
  description: |-
    たっぷり約1.5倍！メロンソーダをたっぷりサイズでお楽しみください。
    ※メロンソーダにメロン果汁は含まれておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &56
  id: '10093'
  name: コーラ　たっぷりサイズ
  description: |-
    たっぷり約1.5倍！コーラをたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &57
  id: '10095'
  name: メロンソーダ　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！メロンソーダをでらたっぷりサイズでお楽しみください。
    ※メロンソーダにメロン果汁は含まれておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &58
  id: '10096'
  name: コーラ　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！コーラをでらたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &59
  id: '10098'
  name: クリームソーダ　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！クリームソーダをでらたっぷりサイズでお楽しみください。
    ※メロンソーダにメロン果汁は含まれておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &64
  id: '10102'
  name: ホットドッグ
  description: たっぷりコールスローとパリッとウインナーを特製ドッグパンで挟みました。
- &65
  id: '10106'
  name: フィッシュフライバーガー
  description: |-
    タルタルソースとチーズが絶妙にマッチ。
    ※本商品に使用しているチーズは加熱処理済みです。
- &66
  id: '10107'
  name: 自慢のドミグラスバーガー
  description: |-
    コメダ特製のドミグラスソースを使用した肉厚パティのハンバーガーです。
    ※本商品に使用しているチーズは加熱処理済みです。
- &67
  id: '10109'
  name: ハムサンド
  description: ロースハムの塩味とピリッときいたからしマヨネーズがアクセントです。
- &68
  id: '10110'
  name: エッグサンド
  description: 手作りたまごペーストがぎっしりと入った、大満足のサンドイッチです。
- &69
  id: '10111'
  name: ポテサラサンド
  description: そのままでもおいしいポテトサラダを野菜とともにサンドしました。
- &70
  id: '10112'
  name: ミックスサンド
  description: 自家製たまごペーストを使った一番人気のサンドイッチです。
- &71
  id: '10113'
  name: ハムトースト
  description: ハムサンドをトーストでもどうぞ。サクッとおいしい食感をお楽しみください。
- &72
  id: '10114'
  name: エッグトースト
  description: エッグサンドをトーストでもどうぞ。サクッとおいしい食感をお楽しみください。
- &73
  id: '10115'
  name: ポテサラトースト
  description: ポテサラサンドをトーストでもどうぞ。サクッとおいしい食感をお楽しみください。
- &74
  id: '10116'
  name: ミックストースト
  description: ミックスサンドをトーストでもどうぞ。サクッとおいしい食感をお楽しみください。
- &75
  id: '10117'
  name: あみ焼きチキンホットサンド
  description: 肉厚チキンとたっぷりキャベツに特製ソースをしみこませました。
- &76
  id: '10118'
  name: ミニコメバスケット
  description: |-
    人気のコメチキ2個とミニサンドを一度に味わえるお得なバスケット。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &77
  id: '10119'
  name: ミニコメバスケット（トースト）
  description: |-
    人気のコメチキとミニサンドを一度に味わえるお得なバスケット。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &78
  id: '10120'
  name: ミニサンド
  description: |-
    手軽さが魅力！ミックスサンドのミニサイズです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &79
  id: '10121'
  name: ミニサンド（トースト）
  description: |-
    手軽さが魅力な定番ミックストーストのミニサイズ。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &80
  id: '10122'
  name: カツパン
  description: 揚げたてサクサクビッグカツとキャベツを豪快に挟みました。
- &81
  id: '10123'
  name: みそカツパン
  description: 揚げたてサクサクビッグカツを名古屋名物濃厚みそダレと合わせてサンドしました。
- &82
  id: '10124'
  name: エビカツパン
  description: プリップリのエビがぎっしり入った自慢のエビカツを、特製サウザンソースでどうぞ。
- &83
  id: '10125'
  name: カツカリーパン
  description: |-
    スパイシーな特製カリーソースと揚げたてサクサクビッグカツがクセになる美味しさです。
    ※やや辛めの商品です。辛い物が苦手な方やお子さまはご注意ください。
- &84
  id: '10127'
  name: カツサンド（沖縄限定）
  description: 揚げたてサクサクビッグカツとキャベツを豪快に挟みました。
- &85
  id: '10128'
  name: みそカツサンド（沖縄限定）
  description: 揚げたてサクサクビッグカツを名古屋名物濃厚みそダレと合わせてサンドしました。
- &86
  id: '10129'
  name: エビカツサンド（沖縄限定）
  description: プリップリのエビがぎっしり入った自慢のエビカツを、特製サウザンソースでどうぞ。
- &87
  id: '10130'
  name: カツカリーサンド（沖縄限定）
  description: |-
    スパイシーな特製カリーソースと揚げたてサクサクビッグカツがクセになる美味しさです。
    ※やや辛めの商品です。辛い物が苦手な方やお子さまはご注意ください。
- &88
  id: '10132'
  name: トースト
  description: 焼き立てのサクふわトーストをお楽しみください。
- &89
  id: '10133'
  name: 小倉トースト
  description: 名古屋の喫茶店めしといえばこちら。焼きたてトーストに小倉あんをのせた絶妙な組み合わせをお楽しみください。
- &90
  id: '10134'
  name: エビフライ
  description: |-
    カラッと揚がったプリプリエビ3尾とたっぷり野菜をお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &91
  id: '10135'
  name: ヒレカツ
  description: |-
    柔らかヒレ肉をサクッと揚げたボリューム満点まんぷくメニューです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &92
  id: '10137'
  name: ジャーマン
  description: |-
    パリッとジューシーなウインナーとたっぷり野菜をお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &93
  id: '10138'
  name: ヒレカツ　ミニサイズ
  description: |-
    柔らかヒレ肉をサクッと揚げました。小腹がすいたときにぴったりのミニサイズでどうぞ。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &94
  id: '10155'
  name: たまとまレタスサンド　コメチキ2ケ付き（単品）
  description: |-
    お昼だけの特別メニューです。コメチキが2つ付いておなかも満足。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &95
  id: '10159'
  name: ミックスサンド　コメチキ2ケ付き（単品）
  description: |-
    お昼だけの特別メニューです。自家製たまごペーストを使った一番人気メニューに、コメチキが2つ付いておなかも満足。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &96
  id: '10161'
  name: ポテサラサンド　コメチキ2ケ付き（単品）
  description: |-
    お昼だけの特別メニューです。そのままでもおいしいポテトサラダを柔らかパンと野菜でさらにおいしく、コメチキが2つ付いておなかも満足。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &97
  id: '10163'
  name: ハムサンド　コメチキ2ケ付き（単品）
  description: |-
    お昼だけの特別メニューです。ロースハムの塩味とピリッときいたからしマヨネーズがアクセント。さらに、コメチキが2つ付いておなかも満足。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &98
  id: '10165'
  name: エッグサンド　コメチキ2ケ付き（単品）
  description: |-
    お昼だけの特別メニューです。手作りたまごペーストがぎっしりと入った、大満足のサンドイッチに、コメチキが2つ付いておなかも満足。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &99
  id: '10171'
  name: "「名古屋名物」あんかけスパ（単品）"
  description: |-
    トロトロの旨辛あんかけがクセになる名古屋名物をどうぞ。
    ※やや辛めの商品です。辛い物が苦手な方やお子さまはご注意ください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &100
  id: '10172'
  name: "「喫茶店の王道」ナポリタン（単品）"
  description: |-
    喫茶店のスパゲッティといえばこちら。定番の味をお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &101
  id: '10173'
  name: "「つぶつぶなめらか」めんたいクリーム（単品）"
  description: |-
    大人気のつぶつぶ明太子スパゲッティにクリームをあわせ、まろやかに仕上げました。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &102
  id: '10174'
  name: "「コクと旨味の本格派」ミートソース（単品）"
  description: |-
    ビーフと野菜のうまみが特徴のミートソースは4種類のスパイスで仕上げたコメダ珈琲店オリジナルです。大人から子供まで楽しめる味わいのスパゲッティです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &103
  id: '10176'
  name: "「旨辛スパイシーカリー」インディアンスパゲッティ（単品）"
  description: |-
    11種類のスパイスで作り上げた特製カリーの虜に。
    ※やや辛めの商品です。辛い物が苦手な方やお子さまはご注意ください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &104
  id: '10177'
  name: サラダバゲット
  description: バゲットパンをガーリックトーストに変更可能です。ご注文時にお申しつけください。
- &105
  id: '10181'
  name: ミニサラダ
  description: |-
    ちょっと食べたい時のバランスサラダ。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &106
  id: '10182'
  name: たっぷりたまごのピザトースト
  description: |-
    たっぷりのたまごペーストととろーりチーズが美味しいふわとろピザトーストです。
    ※本商品に使用しているチーズは加熱処理済みです。
- &107
  id: '10183'
  name: コメダ特製ピザ
  description: |-
    モチモチ生地のオリジナルピザです。
    ※本商品に使用しているチーズは加熱処理済みです。
- &108
  id: '10184'
  name: コメダグラタン
  description: |-
    ふりかけた海苔がアクセント。海老とマカロニのグラタンです。
    ※本商品に使用しているチーズは加熱処理済みです。
- &109
  id: '10185'
  name: ビーフシチュー
  description: |-
    じっくり煮込んだごろごろビーフのシチューに、ポテトサラダとチーズを合わせるのがコメダ流。
    ※本商品に使用しているチーズは加熱処理済みです。
- &110
  id: '10186'
  name: ポテトバスケット
  description: |-
    気軽に食べられる、ちょうどいいボリュームです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
    ※ケチャップ付き
- &111
  id: '10187'
  name: ポテチキ（コメチキ3ケ)
  description: |-
    骨なしジューシーチキン「コメチキ」と揚げポテトが嬉しい一品です。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
    ※ケチャップ付き
- &112
  id: '10188'
  name: コメチキ(6ケ)
  description: フレッシュレモンをしぼって食べる骨なしジューシーチキン。
- &126
  id: '10213'
  name: シロノワール（単品）
  description: |-
    あつあつひえひえの温度差が楽しい、コメダの名物デザートです。
    ※シロノワールのシロップには「はちみつ」が含まれているため、1歳未満の乳児には与えないでください。
- &127
  id: '10216'
  name: ミニシロノワール（単品）
  description: |-
    あつあつひえひえの温度差が楽しい、コメダの名物デザートをミニサイズでどうぞ。おひとり様や、食後のデザートにおすすめです。
    ※ミニシロノワールのシロップには「はちみつ」が含まれているため、1歳未満の乳児には与えないでください。
- &128
  id: '10239'
  name: ソフトクリーム
  description: お皿にのったソフトクリームをスプーンで食べるのがコメダ流です。
- &129
  id: '10240'
  name: 珈琲ジェリー
  description: 自慢のコーヒーで作った自家製ジェリーにバナナとソフトクリームを添えました。ほろ苦い美味しさをどうぞ。
- &130
  id: '10241'
  name: クロネージュ（単品）
  description: |-
    ココア香るバウムクーヘンに冷たいソフトクリームが相性抜群です。
    ※クロネージュのシロップには「はちみつ」が含まれているため、1歳未満の乳児には与えないでください。
- &113
  id: '10332'
  name: カツサンド（持ち帰り限定）
  description: |-
    ずっしり、まんぷく、ボリューム満点カツサンド。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &114
  id: '10333'
  name: みそカツサンド（持ち帰り限定）
  description: |-
    ずっしり、まんぷく、ボリューム満点みそカツサンド。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &115
  id: '10334'
  name: エビカツサンド（持ち帰り限定）
  description: |-
    ずっしり、まんぷく、ボリューム満点エビカツサンド。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &116
  id: '10335'
  name: カツカリーサンド（持ち帰り限定）
  description: |-
    ずっしり、まんぷく、ボリューム満点カツカリーサンド。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &117
  id: '10342'
  name: 本場手羽先　5本入
  description: |-
    「世界のやまちゃん」監修の絶品手羽先。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &118
  id: '10343'
  name: 本場手羽先　10本入
  description: |-
    「世界のやまちゃん」監修の絶品手羽先。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &119
  id: '10384'
  name: ヒレカツ（沖縄限定）
  description: |-
    柔らかヒレ肉をサクッと揚げました。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &120
  id: '10385'
  name: ジャーマン（沖縄限定）
  description: |-
    パリッとジューシーなウインナーとたっぷり野菜。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &60
  id: '10386'
  name: アップルジュース
  description: りんごのおいしさをぎゅっと濃縮したさっぱりとした味わいです。
- &121
  id: '10387'
  name: 手作りたまごドッグ
  description: 自家製たまごペーストとシャキッとレタスのハーモニーをお楽しみください。
- &122
  id: '10453'
  name: 夜コメ　ハイ!チーズ!!プレート　チーズカリーグラタン（単品）
  description: |-
    コメダオリジナルグラタンに新宿中村屋監修のカリーソースを使用。とろーりチーズが食欲を掻き立てる、あつあつの夜限定カリーグラタン。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
    ※お召し上がりの際は、火傷にご注意ください。
    ※やや辛めの商品です。辛い物が苦手な方やお子さまはご注意ください。
    ※本商品に使用しているチーズは加熱処理済みです。
- &123
  id: '10455'
  name: 夜コメ　ハイ!チーズ!!プレート　チーズハンバーグミートスパ（単品）
  description: |-
    とろとろあつあつチーズがたっぷりかかったハンバーグとミートスパゲッティが1つになった、食べごたえ満点の夜限定メニュー。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
    ※お召し上がりの際は、火傷にご注意ください。
    ※本商品に使用しているチーズは加熱処理済みです。
- &124
  id: '10722'
  name: お月見フルムーンバーガー
  description: |-
    月に見立てたとろ〜りエッグオムレツと
    ジューシーハンバーグを、フワフワ食感のバンズでサンド。
    コメダのコクうま、秋の風物詩。

    ※本商品に使用しているチーズは加熱処理済みです。
- &61
  id: '10955'
  name: とろみコーヒー
  description: |-
    とろみがついている分、冷めにくいのでゆったりとくつろぎの時間をお楽しみいただけます。
    ※とろみコーヒーは店舗限定商品です。
- &131
  id: '11052'
  name: 安納芋のスイートポテト シロノワール（単品）
  description: 蜜のようにねっとり甘い、まるでスイートポテトな安納芋ソース。香ばしい黒ごまとご一緒にお楽しみください。※原材料由来の夾雑物が含まれる場合がございます。
- &132
  id: '11053'
  name: 安納芋のスイートポテト シロノワール ミニサイズ（単品）
  description: 蜜のようにねっとり甘い、まるでスイートポテトな安納芋ソース。香ばしい黒ごまとご一緒にお楽しみください。※原材料由来の夾雑物が含まれる場合がございます。
- &133
  id: '11056'
  name: 安納芋のスイートポテト クロネージュ（単品）
  description: ほろ苦ココアバウムを安納芋ソースが優しく包み込んだ秋のデザート。※原材料由来の夾雑物が含まれる場合がございます。
- &62
  id: '11058'
  name: 安納芋のスイートポテト ジェリコ
  description: スイートポテトを思わせるクリーミーな秋のスイーツドリンク。ほろ苦いコーヒージェリーとお楽しみください。※原材料由来の夾雑物が含まれる場合がございます。
- &63
  id: '11059'
  name: 安納芋のスイートポテト オーレ
  description: 安納芋の深い甘みをコーヒーのコクが引き立てる。ほんのり香る黒ごまがアクセント。※原材料由来の夾雑物が含まれる場合がございます。
- &125
  id: '11061'
  name: お月見フルムーンてりやきバーガー
  description: とろ〜りエッグオムレツのお月見フルムーンバーガーをてりやきマヨ仕立てでどうぞ。
- &134
  id: '11063'
  name: 安納芋のモンブラン（単品）
  description: ねっとりとした安納芋の甘みを存分に感じられる逸品。※本商品に使用しているチーズは加熱処理済みです。※原材料由来の夾雑物が含まれる場合がございます。
- &135
  id: '11069'
  name: 魅惑のショコラケーキ（単品）
  description: ほろ苦いショコラタルトに、まろやかショコラクリームを重ねた、大人の味わい。※魅惑のショコラケーキのチョコレート類のうち約80％は、カカオ72％チョコレートを使用しています。
- &136
  id: '11071'
  name: ミルキーミルクレープ（単品）
  description: ミルキーをイメージした特製クリームがなつかしさ感じる味わい。
- &137
  id: '11073'
  name: 純栗ぃむ（単品）
  description: コメダ珈琲店の定番が今年も登場。栗の香りが口いっぱいに広がる、この季節だけの特別。
drinks:
- *1
- *2
- *3
- *4
- *5
- *6
- *7
- *8
- *9
- *10
- *11
- *12
- *13
- *14
- *15
- *16
- *17
- *18
- *19
- *20
- *21
- *22
- *23
- *24
- *25
- *26
- *27
- *28
- *29
- *30
- *31
- *32
- *33
- *34
- *35
- *36
- *37
- *38
- *39
- *40
- *41
- *42
- *43
- *44
- *45
- *46
- *47
- *48
- *49
- *50
- *51
- *52
- *53
- *54
- *55
- *56
- *57
- *58
- *59
- *60
- *61
- *62
- *63
foods:
- *64
- *65
- *66
- *67
- *68
- *69
- *70
- *71
- *72
- *73
- *74
- *75
- *76
- *77
- *78
- *79
- *80
- *81
- *82
- *83
- *84
- *85
- *86
- *87
- *88
- *89
- *90
- *91
- *92
- *93
- *94
- *95
- *96
- *97
- *98
- *99
- *100
- *101
- *102
- *103
- *104
- *105
- *106
- *107
- *108
- *109
- *110
- *111
- *112
- *113
- *114
- *115
- *116
- *117
- *118
- *119
- *120
- *121
- *122
- *123
- *124
- *125
desserts:
- *126
- *127
- *128
- *129
- *130
- *131
- *132
- *133
- *134
- *135
- *136
- *137
