---
all:
- &1
  name: コメダブレンド
  description: 厳選した豆からじっくり丁寧に抽出したコメダ珈琲店伝統の味。濃厚なフレッシュと砂糖の両方を入れるのがオススメです。
- &2
  name: アメリカン
  description: 軽くて飲みやすく、コーヒーの旨味を楽しめます。
- &3
  name: カフェオーレ
  description: やわらかでマイルドな味わい。コーヒーとミルクのこだわりブレンドです。
- &4
  name: ミルクコーヒー
  description: ミルクがいっぱいで飲みやすくまろやかです。
- &5
  name: ウインナーコーヒー
  description: とろけるホイップクリームとコーヒーの深いコクをお楽しみください。
- &6
  name: 蜂蜜オーレウインナー
  description: |-
    蜂蜜の優しい甘さ感じるカフェオーレに、とろけるホイップがよく合う一杯です。
    ※本商品には「はちみつ」を使用しているため、1歳未満の乳児には与えないでください。
- &7
  name: コメ黒
  description: |-
    コクのあるブラジル最上級グレードの豆をベースに華やかに香り高いキリマンジャロをブレンドしました。
    ※ストレートでお楽しみいただくためフレッシュはお付けしておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &8
  name: カフェインレスコーヒー
  description: |-
    良質なコロンビア産の豆を100%使用したコーヒーです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &9
  name: コメダブレンド たっぷりサイズ
  description: いつものコメダブレンドがたっぷり約1.5倍です！
- &10
  name: アメリカン たっぷりサイズ
  description: アメリカンを約1.5倍のたっぷりサイズでお楽しみください。
- &11
  name: カフェオーレ たっぷりサイズ
  description: カフェオーレを約1.5倍のたっぷりサイズでお楽しみください。
- &12
  name: ミルクコーヒー たっぷりサイズ
  description: ミルクコーヒーを約1.5倍のたっぷりサイズでお楽しみください。
- &13
  name: ホットミルク たっぷりサイズ
  description: ミルクを約1.5倍のたっぷりサイズでお楽しみください。
- &14
  name: アイスコーヒー
  description: |-
    独特の味とコクを引きたてるために最初から甘味がついています。ぜひフレッシュも入れてお召し上がりください。
    ※甘味抜き・別添えが可能です。
- &15
  name: アイスオーレ
  description: 深いコクのコーヒーとミルクのハーモニーをお楽しみください。
- &16
  name: アイスミルクコーヒー
  description: コーヒーとミルクのやさしい味わいをアイスでもどうぞ。
- &17
  name: アイスウインナー
  description: アイスコーヒーに相性抜群のホイップをのせました。
- &18
  name: クリームコーヒー
  description: アイスコーヒーにソフトクリームの山がそびえ立ちます。
- &19
  name: クリームオーレ
  description: アイスオーレにソフトクリームの山がそびえ立ちます。
- &20
  name: 蜂蜜アイスコーヒー
  description: |-
    蜂蜜の香りと甘みがコーヒーの旨味をぐっと引きたてます。
    ※本商品には「はちみつ」を使用しているため、1歳未満の乳児には与えないでください。
- &21
  name: ジェリコ 元祖
  description: コーヒージェリーとアイスコーヒーを組み合わせて、仕上げにホイップをのせたほろ苦い大人の飲むスイーツ。
- &22
  name: カフェインレスアイスコーヒー
  description: |-
    良質なコロンビア産の豆を100%使用したアイスコーヒーです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &23
  name: プレミアムコーヒー Sophia
  description: |-
    程よい苦味とやわらかな酸味雑味がなく、コクはありながらすっきりとした後味。
    ※ストレートでお楽しみいただくためフレッシュはお付けしておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &24
  name: アイスコーヒー たっぷりサイズ
  description: たっぷり約1.5倍！特製ジョッキでお楽しみください。
- &25
  name: アイスオーレ たっぷりサイズ
  description: たっぷり約1.5倍！アイスオーレをたっぷりサイズでお楽しみください。
- &26
  name: アイスミルクコーヒー たっぷりサイズ
  description: たっぷり約1.5倍！アイスミルクコーヒーをたっぷりサイズでお楽しみください。
- &27
  name: アイスミルク たっぷりサイズ
  description: たっぷり約1.5倍！アイスミルクをたっぷりサイズでお楽しみください。
- &28
  name: アイスコーヒー　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！アイスコーヒーをでらたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &29
  name: アイスオーレ　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！アイスオーレをでらたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &30
  name: アイスミルクコーヒー　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！アイスミルクコーヒーをでらたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &31
  name: アイスミルク　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！アイスミルクをでらたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &32
  name: 紅茶　レモン
  description: レモンティーでお楽しみください。
- &33
  name: 紅茶　ミルク
  description: ミルクティーでお楽しみください。
- &34
  name: 紅茶　ストレート
  description: スリランカ産茶葉使用。
- &35
  name: お伊勢さんの和紅茶 「瑞」
  description: "三重県産の茶葉を使用した風味豊かな和紅茶です。ポットでお楽しみいただけます。  \n※この商品には紅茶の風味を引きたてるためにスリランカ産茶葉も使用しております。\n※ポットサービスはホットのみとなります。\n※紅茶本来の風味をお楽しみいただくため、ストレートのみでの提供となります。\n※店舗により販売状況が異なります。詳しくは店舗にご確認ください。"
- &36
  name: アイスレモンティー
  description: レモンティーでお楽しみください。
- &37
  name: アイスミルクティー
  description: ミルクティーでお楽しみください。
- &38
  name: アイスストレートティー
  description: アールグレイです。
- &39
  name: お伊勢さんの和紅茶 「瑞」アイス
  description: "三重県産の茶葉を使用した風味豊かな和紅茶です。 \n※この商品には紅茶の風味を引きたてるためにスリランカ産茶葉も使用しております。\n※ポットサービスはホットのみとなります。\n※紅茶本来の風味をお楽しみいただくため、ストレートのみでの提供となります。\n※店舗により販売状況が異なります。詳しくは店舗にご確認ください。"
- &40
  name: ホットミルク
  description: ほっと落ち着く、やさしい味わいです。
- &41
  name: アイスミルク
  description: ほのかに甘く、お子様にもおすすめです。
- &42
  name: コーンスープ
  description: じんわり温かくやさしい味わいです。お食事と一緒にどうぞ。
- &43
  name: ホットココア
  description: カカオが香るクリーミーなココアに、ホイップクリームを載せた贅沢な一杯です。
- &44
  name: アイスココア
  description: アイスココアの上にソフトクリームがそびえ立ちます。
- &45
  name: メロンソーダ
  description: |-
    メロンソーダを見た目も可愛いブーツグラスでどうぞ。
    ※メロンソーダにメロン果汁は含まれておりません。
- &46
  name: クリームソーダ
  description: |-
    懐かしのクリームソーダを見た目も可愛いブーツグラスでどうぞ。
    ※メロンソーダにメロン果汁は含まれておりません。
- &47
  name: コーラ
  description: どの年代にも人気の炭酸ドリンクです。レモンを添えた喫茶店風をお楽しみください。
- &48
  name: オレンジジュース
  description: 果汁100%(濃縮還元)のオレンジジュース。まんまるだるまグラスで気分もウキウキ！
- &49
  name: ミックスジュース
  description: フルーツとミルクで美味しく仕上げました。
- &50
  name: サマージュース
  description: |-
    甘夏のつぶつぶ食感が楽しい特製ジュースです。
    ※甘夏果汁約30％使用。
- &51
  name: 生レモンスカッシュ
  description: 新鮮なレモンをギュッとしぼった爽やかな味わいです。コロンと可愛いブーツグラスでどうぞ。
- &52
  name: コーヒーシェーク
  description: ソフトクリームがとろける、タル製グラスに入ったコーヒー風味の特製デザートドリンクです。
- &53
  name: ストロベリーシェーク
  description: ソフトクリームがとろける、イチゴ風味のコメダ特製飲むデザートです。※ストロベリーシェークにいちご果汁は含まれておりません。
- &54
  name: バナナジュース
  description: バナナとミルクで美味しく仕上げました。
- &55
  name: メロンソーダ　たっぷりサイズ
  description: |-
    たっぷり約1.5倍！メロンソーダをたっぷりサイズでお楽しみください。
    ※メロンソーダにメロン果汁は含まれておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &56
  name: コーラ　たっぷりサイズ
  description: |-
    たっぷり約1.5倍！コーラをたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &57
  name: メロンソーダ　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！メロンソーダをでらたっぷりサイズでお楽しみください。
    ※メロンソーダにメロン果汁は含まれておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &58
  name: コーラ　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！コーラをでらたっぷりサイズでお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &59
  name: クリームソーダ　でらたっぷりサイズ
  description: |-
    でらたっぷり約2倍！クリームソーダをでらたっぷりサイズでお楽しみください。
    ※メロンソーダにメロン果汁は含まれておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &63
  name: ホットドッグ
  description: たっぷりコールスローとパリッとウインナーを特製ドッグパンで挟みました。
- &64
  name: フィッシュフライバーガー
  description: |-
    タルタルソースとチーズが絶妙にマッチ。
    ※本商品に使用しているチーズは加熱処理済みです。
- &65
  name: 自慢のドミグラスバーガー
  description: |-
    コメダ特製のドミグラスソースを使用した肉厚パティのハンバーガーです。
    ※本商品に使用しているチーズは加熱処理済みです。
- &66
  name: ハムサンド
  description: ロースハムの塩味とピリッときいたからしマヨネーズがアクセントです。
- &67
  name: エッグサンド
  description: 手作りたまごペーストがぎっしりと入った、大満足のサンドイッチです。
- &68
  name: ポテサラサンド
  description: そのままでもおいしいポテトサラダを野菜とともにサンドしました。
- &69
  name: ミックスサンド
  description: 自家製たまごペーストを使った一番人気のサンドイッチです。
- &70
  name: ハムトースト
  description: ハムサンドをトーストでもどうぞ。サクッとおいしい食感をお楽しみください。
- &71
  name: エッグトースト
  description: エッグサンドをトーストでもどうぞ。サクッとおいしい食感をお楽しみください。
- &72
  name: ポテサラトースト
  description: ポテサラサンドをトーストでもどうぞ。サクッとおいしい食感をお楽しみください。
- &73
  name: ミックストースト
  description: ミックスサンドをトーストでもどうぞ。サクッとおいしい食感をお楽しみください。
- &74
  name: あみ焼きチキンホットサンド
  description: 肉厚チキンとたっぷりキャベツに特製ソースをしみこませました。
- &75
  name: ミニコメバスケット
  description: |-
    人気のコメチキ2個とミニサンドを一度に味わえるお得なバスケット。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &76
  name: ミニコメバスケット（トースト）
  description: |-
    人気のコメチキとミニサンドを一度に味わえるお得なバスケット。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &77
  name: ミニサンド
  description: |-
    手軽さが魅力！ミックスサンドのミニサイズです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &78
  name: ミニサンド（トースト）
  description: |-
    手軽さが魅力な定番ミックストーストのミニサイズ。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &79
  name: カツパン
  description: 揚げたてサクサクビッグカツとキャベツを豪快に挟みました。
- &80
  name: みそカツパン
  description: 揚げたてサクサクビッグカツを名古屋名物濃厚みそダレと合わせてサンドしました。
- &81
  name: エビカツパン
  description: プリップリのエビがぎっしり入った自慢のエビカツを、特製サウザンソースでどうぞ。
- &82
  name: カツカリーパン
  description: |-
    スパイシーな特製カリーソースと揚げたてサクサクビッグカツがクセになる美味しさです。
    ※やや辛めの商品です。辛い物が苦手な方やお子さまはご注意ください。
- &83
  name: カツサンド（沖縄限定）
  description: 揚げたてサクサクビッグカツとキャベツを豪快に挟みました。
- &84
  name: みそカツサンド（沖縄限定）
  description: 揚げたてサクサクビッグカツを名古屋名物濃厚みそダレと合わせてサンドしました。
- &85
  name: エビカツサンド（沖縄限定）
  description: プリップリのエビがぎっしり入った自慢のエビカツを、特製サウザンソースでどうぞ。
- &86
  name: カツカリーサンド（沖縄限定）
  description: |-
    スパイシーな特製カリーソースと揚げたてサクサクビッグカツがクセになる美味しさです。
    ※やや辛めの商品です。辛い物が苦手な方やお子さまはご注意ください。
- &87
  name: トースト
  description: 焼き立てのサクふわトーストをお楽しみください。
- &88
  name: 小倉トースト
  description: 名古屋の喫茶店めしといえばこちら。焼きたてトーストに小倉あんをのせた絶妙な組み合わせをお楽しみください。
- &89
  name: エビフライ
  description: |-
    カラッと揚がったプリプリエビ3尾とたっぷり野菜をお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &90
  name: ヒレカツ
  description: |-
    柔らかヒレ肉をサクッと揚げたボリューム満点まんぷくメニューです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &91
  name: ジャーマン
  description: |-
    パリッとジューシーなウインナーとたっぷり野菜をお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &92
  name: ヒレカツ　ミニサイズ
  description: |-
    柔らかヒレ肉をサクッと揚げました。小腹がすいたときにぴったりのミニサイズでどうぞ。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &93
  name: たまとまレタスサンド　コメチキ2ケ付き（単品）
  description: |-
    お昼だけの特別メニューです。コメチキが2つ付いておなかも満足。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &94
  name: ミックスサンド　コメチキ2ケ付き（単品）
  description: |-
    お昼だけの特別メニューです。自家製たまごペーストを使った一番人気メニューに、コメチキが2つ付いておなかも満足。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &95
  name: ポテサラサンド　コメチキ2ケ付き（単品）
  description: |-
    お昼だけの特別メニューです。そのままでもおいしいポテトサラダを柔らかパンと野菜でさらにおいしく、コメチキが2つ付いておなかも満足。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &96
  name: ハムサンド　コメチキ2ケ付き（単品）
  description: |-
    お昼だけの特別メニューです。ロースハムの塩味とピリッときいたからしマヨネーズがアクセント。さらに、コメチキが2つ付いておなかも満足。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &97
  name: エッグサンド　コメチキ2ケ付き（単品）
  description: |-
    お昼だけの特別メニューです。手作りたまごペーストがぎっしりと入った、大満足のサンドイッチに、コメチキが2つ付いておなかも満足。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &98
  name: "「名古屋名物」あんかけスパ（単品）"
  description: |-
    トロトロの旨辛あんかけがクセになる名古屋名物をどうぞ。
    ※やや辛めの商品です。辛い物が苦手な方やお子さまはご注意ください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &99
  name: "「喫茶店の王道」ナポリタン（単品）"
  description: |-
    喫茶店のスパゲッティといえばこちら。定番の味をお楽しみください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &100
  name: "「つぶつぶなめらか」めんたいクリーム（単品）"
  description: |-
    大人気のつぶつぶ明太子スパゲッティにクリームをあわせ、まろやかに仕上げました。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &101
  name: "「コクと旨味の本格派」ミートソース（単品）"
  description: |-
    ビーフと野菜のうまみが特徴のミートソースは4種類のスパイスで仕上げたコメダ珈琲店オリジナルです。大人から子供まで楽しめる味わいのスパゲッティです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &102
  name: "「旨辛スパイシーカリー」インディアンスパゲッティ（単品）"
  description: |-
    11種類のスパイスで作り上げた特製カリーの虜に。
    ※やや辛めの商品です。辛い物が苦手な方やお子さまはご注意ください。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &103
  name: サラダバゲット
  description: バゲットパンをガーリックトーストに変更可能です。ご注文時にお申しつけください。
- &104
  name: ミニサラダ
  description: |-
    ちょっと食べたい時のバランスサラダ。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &105
  name: たっぷりたまごのピザトースト
  description: |-
    たっぷりのたまごペーストととろーりチーズが美味しいふわとろピザトーストです。
    ※本商品に使用しているチーズは加熱処理済みです。
- &106
  name: コメダ特製ピザ
  description: |-
    モチモチ生地のオリジナルピザです。
    ※本商品に使用しているチーズは加熱処理済みです。
- &107
  name: コメダグラタン
  description: |-
    ふりかけた海苔がアクセント。海老とマカロニのグラタンです。
    ※本商品に使用しているチーズは加熱処理済みです。
- &108
  name: ビーフシチュー
  description: |-
    じっくり煮込んだごろごろビーフのシチューに、ポテトサラダとチーズを合わせるのがコメダ流。
    ※本商品に使用しているチーズは加熱処理済みです。
- &109
  name: ポテトバスケット
  description: |-
    気軽に食べられる、ちょうどいいボリュームです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
    ※ケチャップ付き
- &110
  name: ポテチキ（コメチキ3ケ)
  description: |-
    骨なしジューシーチキン「コメチキ」と揚げポテトが嬉しい一品です。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
    ※ケチャップ付き
- &111
  name: コメチキ(6ケ)
  description: フレッシュレモンをしぼって食べる骨なしジューシーチキン。
- &123
  name: シロノワール（単品）
  description: |-
    あつあつひえひえの温度差が楽しい、コメダの名物デザートです。
    ※シロノワールのシロップには「はちみつ」が含まれているため、1歳未満の乳児には与えないでください。
- &124
  name: ミニシロノワール（単品）
  description: |-
    あつあつひえひえの温度差が楽しい、コメダの名物デザートをミニサイズでどうぞ。おひとり様や、食後のデザートにおすすめです。
    ※ミニシロノワールのシロップには「はちみつ」が含まれているため、1歳未満の乳児には与えないでください。
- &125
  name: いちご氷
  description: "みんなに愛される定番のいちご氷。練乳、ソフトクリームのトッピングとぜひご一緒にどうぞ。\t\t\t\n※トッピングなしの価格です。\n※トッピングは、ソフトクリーム(120円)、練乳（80円）が可能です。\n※写真はトッピングなしです。\n※店舗により販売状況が異なります。詳しくは店舗にご確認ください。\n※いちご果汁は含まれておりません。"
- &126
  name: 宇治抹茶氷
  description: "風味豊かな宇治抹茶を100%使用したシロップ。\t\t\t\t\t\n抹茶の香りが口いっぱいに広がるすっきりとした味わい。\t\t\t\t\t\n※トッピングなしの価格です。\n※トッピングは、ソフトクリーム／小倉あん(120円)、練乳（80円）が可能です。\n※写真はトッピングなしです。\n※店舗により販売状況が異なります。詳しくは店舗にご確認ください。"
- &127
  name: いちご氷 ミニサイズ
  description: "みんなに愛される定番のいちご氷。\t\t\t\n練乳、ソフトクリームのトッピングとぜひご一緒にどうぞ。\nミニサイズもおすすめ。\n※トッピングなしの価格です。\n※トッピングは、ソフトクリーム(120円)、練乳（80円）が可能です。\n※写真はトッピングなしです。\n※店舗により販売状況が異なります。詳しくは店舗にご確認ください。\n※いちご果汁は含まれておりません。"
- &128
  name: 宇治抹茶氷 ミニサイズ
  description: "風味豊かな宇治抹茶を100%使用したシロップ。\t\t\t\t\t\n抹茶の香りが口いっぱいに広がるすっきりとした味わい。\t\nミニサイズもおすすめ。\n※トッピングなしの価格です。\n※トッピングは、ソフトクリーム／小倉あん(120円)、練乳（80円）が可能です。\n※写真はトッピングなしです。\n※店舗により販売状況が異なります。詳しくは店舗にご確認ください。"
- &129
  name: ソフトクリーム
  description: お皿にのったソフトクリームをスプーンで食べるのがコメダ流です。
- &130
  name: 珈琲ジェリー
  description: 自慢のコーヒーで作った自家製ジェリーにバナナとソフトクリームを添えました。ほろ苦い美味しさをどうぞ。
- &131
  name: クロネージュ（単品）
  description: |-
    ココア香るバウムクーヘンに冷たいソフトクリームが相性抜群です。
    ※クロネージュのシロップには「はちみつ」が含まれているため、1歳未満の乳児には与えないでください。
- &112
  name: カツサンド（持ち帰り限定）
  description: |-
    ずっしり、まんぷく、ボリューム満点カツサンド。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &113
  name: みそカツサンド（持ち帰り限定）
  description: |-
    ずっしり、まんぷく、ボリューム満点みそカツサンド。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &114
  name: エビカツサンド（持ち帰り限定）
  description: |-
    ずっしり、まんぷく、ボリューム満点エビカツサンド。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &115
  name: カツカリーサンド（持ち帰り限定）
  description: |-
    ずっしり、まんぷく、ボリューム満点カツカリーサンド。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &116
  name: 本場手羽先　5本入
  description: |-
    「世界のやまちゃん」監修の絶品手羽先。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &117
  name: 本場手羽先　10本入
  description: |-
    「世界のやまちゃん」監修の絶品手羽先。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &118
  name: ヒレカツ（沖縄限定）
  description: |-
    柔らかヒレ肉をサクッと揚げました。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &119
  name: ジャーマン（沖縄限定）
  description: |-
    パリッとジューシーなウインナーとたっぷり野菜。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &60
  name: アップルジュース
  description: りんごのおいしさをぎゅっと濃縮したさっぱりとした味わいです。
- &120
  name: 手作りたまごドッグ
  description: 自家製たまごペーストとシャキッとレタスのハーモニーをお楽しみください。
- &121
  name: 夜コメ　ハイ!チーズ!!プレート　チーズカリーグラタン（単品）
  description: |-
    コメダオリジナルグラタンに新宿中村屋監修のカリーソースを使用。とろーりチーズが食欲を掻き立てる、あつあつの夜限定カリーグラタン。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
    ※お召し上がりの際は、火傷にご注意ください。
    ※やや辛めの商品です。辛い物が苦手な方やお子さまはご注意ください。
    ※本商品に使用しているチーズは加熱処理済みです。
- &122
  name: 夜コメ　ハイ!チーズ!!プレート　チーズハンバーグミートスパ（単品）
  description: |-
    とろとろあつあつチーズがたっぷりかかったハンバーグとミートスパゲッティが1つになった、食べごたえ満点の夜限定メニュー。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
    ※お召し上がりの際は、火傷にご注意ください。
    ※本商品に使用しているチーズは加熱処理済みです。
- &132
  name: ブルーハワイ氷
  description: |-
    鮮やかで美しいマリンブルーカラーのシロップです。
    爽やかな後味で南国気分がお楽しみいただけます。
    ※トッピングなしの価格です。
    ※トッピングは、ソフトクリーム(120円)、練乳（80円）が可能です。
    ※写真はトッピングなしです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &133
  name: ブルーハワイ氷 ミニサイズ
  description: |-
    鮮やかで美しいマリンブルーカラーのシロップです。
    爽やかな後味で南国気分がお楽しみいただけます。
    ミニサイズもおすすめ。
    ※トッピングなしの価格です。
    ※トッピングは、ソフトクリーム(120円)、練乳（80円）が可能です。
    ※写真はトッピングなしです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &134
  name: レモン氷
  description: |-
    レモン風味の爽やかな香り広がる、清涼感あふれるかき氷。
    さっぱりとした味わいなので爽やかな酸味と優しい甘みが特徴です。
    ※トッピングなしの価格です。
    ※トッピングは、ソフトクリーム(120円)、練乳（80円）が可能です。
    ※写真はトッピングなしです。
    ※レモン果汁は含まれておりません。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
- &135
  name: レモン氷 ミニサイズ
  description: |-
    レモン風味の爽やかな香り広がる、清涼感あふれるかき氷。
    さっぱりとした味わいなので爽やかな酸味と優しい甘みが特徴です。
    ミニサイズもおすすめ。
    ※トッピングなしの価格です。
    ※トッピングは、ソフトクリーム(120円)、練乳（80円）が可能です。
    ※写真はトッピングなしです。
    ※店舗により販売状況が異なります。詳しくは店舗にご確認ください。
    ※レモン果汁は含まれておりません。
- &136
  name: シロノワール　天空の抹茶（単品）
  description: 奥深い甘みの「天空の抹茶」を使用した抹茶ソースに、ソフトクリームと黒蜜ソースがとろけあう一品。折り重なる旨味と甘味を引き立てる、香ばしいきな粉の香りが広がります。
- &137
  name: シロノワール　天空の抹茶　ミニサイズ（単品）
  description: 奥深い甘みの「天空の抹茶」を使用した抹茶ソースに、ソフトクリームと黒蜜ソースがとろけあう一品。折り重なる旨味と甘味を引き立てる、香ばしいきな粉の香りが広がります。お一人様にはミニもおすすめ。
- &138
  name: クロネージュ　天空の抹茶（単品）
  description: ほろ苦いココアバウムクーヘンとコク深い天空の抹茶ソースの絶妙なハーモニーをお楽しみください。
- &61
  name: ジェリコ　天空の抹茶
  description: 味わい深く、香り高い「天空の抹茶」をコーヒージェリーと楽しむ、ほろ苦いドリンク。
- &62
  name: とろみコーヒー
  description: |-
    とろみがついている分、冷めにくいのでゆったりとくつろぎの時間をお楽しみいただけます。
    ※とろみコーヒーは店舗限定商品です。
- &139
  name: ふわるシャインマスカットシフォン（単品）
  description: ソースからクリーム、スポンジまで、すべてにシャインマスカットを使用。爽やかでフルーティーな果実の味わいを、最後の一口まで。※天面のソースにブドウの種(黒点)が入ることがございます。
- &140
  name: すずむレモンチーズ（単品）
  description: レモンソースをまとったレアチーズケーキを夏にうれしい冷たさで。一口ほおばれば、ひんやり気分もリフレッシュ。※本商品はリステリアフリーです。
- &141
  name: かおる紅茶モンブラン（単品）
  description: 口に入れた瞬間広がる、アールグレイの華やかな香り。隠れたオレンジピューレがアクセント。※本商品に使用しているチーズは加熱処理済みです。
drinks:
- *1
- *2
- *3
- *4
- *5
- *6
- *7
- *8
- *9
- *10
- *11
- *12
- *13
- *14
- *15
- *16
- *17
- *18
- *19
- *20
- *21
- *22
- *23
- *24
- *25
- *26
- *27
- *28
- *29
- *30
- *31
- *32
- *33
- *34
- *35
- *36
- *37
- *38
- *39
- *40
- *41
- *42
- *43
- *44
- *45
- *46
- *47
- *48
- *49
- *50
- *51
- *52
- *53
- *54
- *55
- *56
- *57
- *58
- *59
- *60
- *61
- *62
foods:
- *63
- *64
- *65
- *66
- *67
- *68
- *69
- *70
- *71
- *72
- *73
- *74
- *75
- *76
- *77
- *78
- *79
- *80
- *81
- *82
- *83
- *84
- *85
- *86
- *87
- *88
- *89
- *90
- *91
- *92
- *93
- *94
- *95
- *96
- *97
- *98
- *99
- *100
- *101
- *102
- *103
- *104
- *105
- *106
- *107
- *108
- *109
- *110
- *111
- *112
- *113
- *114
- *115
- *116
- *117
- *118
- *119
- *120
- *121
- *122
desserts:
- *123
- *124
- *125
- *126
- *127
- *128
- *129
- *130
- *131
- *132
- *133
- *134
- *135
- *136
- *137
- *138
- *139
- *140
- *141
