name: Diff menus reporter

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - config/menus.yaml

jobs:
  comment:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: comment
        run: gh pr comment ${{ github.event.pull_request.number }} -b "$(ruby script/diff_menus.rb)" --repo ${{ github.repository }}
