name: Release

on:
  push:
    #  tags:
    #  - v*
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.4
      - run: |
          git fetch --depth 1
          #export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          #LATEST_TAG=$(gh api repos/${GITHUB_REPOSITORY}/tags | jq -r '.[0].name')
          #echo "Latest tag is $LATEST_TAG"
          #git fetch --depth=1 origin tag ${LATEST_TAG}
      - run: git tag
      #- uses: rubygems/release-gem@v1
