name: Release

on:
  push:
    branches:
      - main
    paths:
      - lib/komeda/version.rb
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.4
      - name: Sleep 30 seconds before release
        run: sleep 30
      - uses: rubygems/release-gem@v1
